spring:
  application:
    name: inventory-service

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8082
  servlet:
    context-path: /api/inventory-service/v1

aws:
  dynamodb:
    table-name: INVENTORY
  sns:
    order-topic-arn: arn:aws:sns:us-east-1:200849340204:order-events
  s3:
    bucket-name: marketplace-dev-fredfmelo
    presigned-url-expiration-minutes: 15
  sqs:
    inventory-queue: inventory-queue
